apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: ole-TEST
spec:
  environments:
    - name: qa
      build:
        from: master
    - name: test
      build:
        from: master
  components:
    - name: server
      src: .
      publicPort: http
      ports:
       - name: http
         port: 8080
      public: true
      environmentConfig:
        - environment: qa
          runAsNonRoot: false
          replicas: 1
          resources:
            requests:
              memory: "40Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
              cpu: "20m"
        - environment: test
          runAsNonRoot: true
          replicas: 1
          resources:
            requests:
              memory: "40Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
              cpu: "20m"