apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: ole-TEST
spec:
  environments:
    - name: test
      build:
        from: master
    - name: prod
  components:
    - name: app
      src: "."
      publicPort: http
      ports:
       - name: http
         port: 8000
      public: true
      environmentConfig:
        - environment: qa
          replicas: 1
