apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: ole-TEST
spec:
  environments:
    - name: qa
      build:
        from: master
  components:
    - name: first-server
      src: "."
      dockerfileName: "./api/Dockerfile"
      publicPort: http
      ports:
       - name: http
         port: 8000
      public: true
      environmentConfig:
        - environment: qa
          replicas: 1
          resources:
            requests:
              memory: "40Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
              cpu: "20m"
    - name: second-server
      src: "."
      dockerfileName: "./another-api/Dockerfile"
      publicPort: http
      ports:
       - name: http
         port: 8000
      public: true
      environmentConfig:
        - environment: qa
          replicas: 1
          resources:
            requests:
              memory: "40Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
              cpu: "20m"
    - name: frontend
      src: "."
      dockerfileName: "./third-api/Dockerfile"
      publicPort: http
      ports:
       - name: http
         port: 8000
      public: true
      environmentConfig:
        - environment: qa
          replicas: 1
          resources:
            requests:
              memory: "40Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
              cpu: "20m"
    - name: second-frontend
      src: "."
      dockerfileName: "./fourth-api/Dockerfile"
      publicPort: http
      ports:
       - name: http
         port: 8000
      public: true
      environmentConfig:
        - environment: qa
          replicas: 1
          resources:
            requests:
              memory: "40Mi"
              cpu: "10m"
            limits:
              memory: "50Mi"
              cpu: "20m"
