apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: ole-TEST
spec:
  environments:
    - name: qa
      build:
        from: master
  components:
    - name: app
      secrets:
        - WHITELIST
      src: "."
      publicPort: http
      ports:
       - name: http
         port: 80
      public: true
      environmentConfig:
        - environment: qa
          replicas: 1
